---
name: "Jellyfin.Plugin.HomeMessage"
guid: "69d36d38-5615-4128-b2e0-30caf4c5ba86"
version: "0.1.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "A Jellyfin plugin that displays messages on the home page."
description: >
  Adds admin-configurable messages to the Jellyfin home page,
  with scheduling and per-user dismiss tracking.
category: "General"
owner: "headzoo"
artifacts:
  - Jellyfin.Plugin.HomeMessage.dll
  - AngleSharp.dll
changelog: >
  changelog
