name: '🚀 Publish Plugin'
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create/release (for manual runs)'
        required: false
      prerelease:
        type: boolean
        default: false
        description: 'Mark as prerelease (manual runs only)'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Web build
        uses: ./.github/actions/web-build
        with:
          typecheck: 'false'  # optional; speed up publish

      - name: Package (JPRM)
        id: pkg
        uses: ./.github/actions/jellyfin-package
        with:
          dotnet-target: net8.0

      # If triggered by a Release, just attach to that release
      - name: Upload to existing release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.pkg.outputs.artifact }}

      # If triggered manually, create the release
      - name: Create release & upload
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag || format('manual-{0}', github.run_number) }}
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true
          files: ${{ steps.pkg.outputs.artifact }}

      - name: Generate & publish manifest.json
        uses: Kevinjil/jellyfin-plugin-repo-action@v0.4.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pagesBranch: main
          pagesFile: docs/manifest.json
          repository: headzoo/jellyfin-plugin-homemessage
