name: "🧪 Test Plugin"

on:
  push:
    branches: [ main ]
    paths-ignore: [ "**/*.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**/*.md" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Jellyfin.Plugin.HomeMessage.sln

      - name: Build
        run: dotnet build Jellyfin.Plugin.HomeMessage.sln -c Release --no-restore

      # 👇 Point directly to your test project (rename path if needed)
      - name: Test
        run: |
          dotnet test Jellyfin.Plugin.HomeMessage.Tests/Jellyfin.Plugin.HomeMessage.Tests.csproj \
            -c Release --no-build \
            --logger "console;verbosity=normal;summary=true" \
            --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults.trx
